name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Laravel app
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            # Change directory to your Laravel application path
            cd /var/www/html/LaravelAPI  # แก้ไข path นี้ตามที่คุณใช้จริง
            # Pull the latest code from the main branch
            git pull origin main
            # Install PHP dependencies
            composer install --no-interaction --prefer-dist --optimize-autoloader
            # Run Laravel migrations
            php artisan migrate --force
            # Cache configuration, routes, and views
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            # Optional: Restart the web server
            sudo systemctl restart nginx
            echo 'Deployment successful to DigitalOcean'
